Step 1 - Prepare the Dataset

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Students_Records.csv to Students_Records.csv

Step 2 - Read the Data

In [2]:
import pandas as pd

df = pd.read_csv('Students_Records.csv')
df.head()

   Student_ID     Name Department  Maths  Physics  Chemistry  Attendance
0         201   Naveen         ML     98       96         99          89
1         202   Nithin         ME     87       95         76          86
2         203    Aryan         ES     86       93         95          98
3         204  Abhinav         CH     95       56         84          98
4         205   Rajesh         ME     94       94         63          76

Step 3 - Process the Data

In [19]:
import pandas as pd
import numpy as np

subjects = ["Maths","Physics","Chemistry"]

df["Total"] = df[subjects].sum(axis=1)
df["Average"] = df[subjects].mean(axis=1)

grades = []

for average in df["Average"]:
    if average >= 90:
        grade = "A+"
    elif average >= 80:
        grade = "A"
    elif average >= 70:
        grade = "B"
    elif average >= 60:
        grade = "C"
    elif average >= 50:
        grade = "D"
    else:
        grade = "F"

    grades.append(grade)

df["Grade"] = grades

pass_fail = []

for i in range(len(df)):
    if (df.loc[i, "Maths"] >= 40 and
        df.loc[i, "Physics"] >= 40 and
        df.loc[i, "Chemistry"] >= 40 and
        df.loc[i, "Attendance"] >= 75):
        pass_fail.append("Pass")
    else:
        pass_fail.append("Fail")

df["Pass_Fail"] = pass_fail

df[["Student_ID","Name","Total","Average","Grade","Pass_Fail"]]

    Student_ID        Name  Total    Average Grade Pass_Fail
0          201      Naveen    293  97.666667    A+      Pass
1          202      Nithin    258  86.000000     A      Pass
2          203       Aryan    274  91.333333    A+      Pass
3          204     Abhinav    235  78.333333     B      Pass
4          205      Rajesh    251  83.666667     A      Pass
5          206     Krishna    207  69.000000     C      Fail
6          207    Vishakha    165  55.000000     D      Fail
7          208      Bhumai    232  77.333333     B      Pass
8          209       Glory    183  61.000000     C      Fail
9          210       Sahil    179  59.666667     D      Fail
10         211     Hitarth    249  83.000000     A      Pass
11         212       Parth    226  75.333333     B      Pass
12         213      Jaywal    189  63.000000     C      Fail
13         214       Bhanu    237  79.000000     B      Fail
14         215       Ayyub    235  78.333333     B      Pass
15         216      Yamuna    257  85.666667     A      Pass
16         217     Kalpana    235  78.333333     B      Pass
17         218  Radhashyam    197  65.666667     C      Fail
18         219     Thrilok    186  62.000000     C      Pass
19         220       Nemil    225  75.000000     B      Pass

Step 4 - Perform Analysis

In [21]:
highest_student = df.loc[df["Average"].idxmax(),"Name"]
print("Top Student is ",highest_student)

highest_average = df["Average"].max()
print("Highest Average :" ,highest_average)

subject_averages = df[subjects].mean()
best_subject = subject_averages.idxmax()
best_average = subject_averages.max()

print("All subjects averages :\n",subject_averages)
print("Best performance Subject is :",best_subject)
print("The best average is :",best_average)

passed_students = (df["Pass_Fail"] == "Pass").sum()
failed_students = (df["Pass_Fail"] == "Fail").sum()

print(f"Passed Students: {passed_students} | Failed Students: {failed_students}")

Top Student is  Naveen
Highest Average : 97.66666666666667
All subjects averages :
 Maths        77.20
Physics      73.10
Chemistry    75.35
dtype: float64
Best performance Subject is : Maths
The best average is : 77.2
Passed Students: 13 | Failed Students: 7